version: "3.9"

services:
  # client:

  # server:

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
    command: --default-authentication-plugin=mysql_native_password

volumes:
  data:
