version: '3.9'

services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin
    command: --default-authentication-plugin=mysql_native_password

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"

  server:
    build:
      dockerfile: Dockerfile
      context: server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mysql

    # client:
    #   build:
    #     dockerfile: ./client/Dockerfile
    #     context: client
    #   container_name: client
    #   ports:
    #     - "3000:3000"
    #   volumes:
    #     - ./client/src:/app/src
    #   depends_on:
    #     - mysql

volumes:
  data:
