POST http://localhost:5000/api/v1/items HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "image" : "image",
  "price" : 0.8008281904610115,
  "name" : "name",
  "description" : "description"
}

###
GET http://localhost:5000/api/v1/items HTTP/1.1
Accept: application/json
Content-Type: application/json

### 
GET http://localhost:5000/api/v1/items/0 HTTP/1.1
Accept: application/json
Content-Type: application/json

###
PUT http://localhost:5000/api/v1/items/0 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
  "image" : "image",
  "price" : 0.8008281904610115,
  "name" : "name",
  "description" : "description"
}

### 
DELETE http://localhost:5000/api/v1/items/0 HTTP/1.1
Accept: application/json
Content-Type: application/json