######################################################
# Get one by ID
GET http://localhost:5000/api/v1/items/0
Accept: application/json

###
GET http://localhost:5000/api/v1/offers/0
Accept: application/json

###
GET http://localhost:5000/api/v1/entities/0
Accept: application/json

######################################################
# Get All
GET http://localhost:5000/api/v1/items
Accept: application/json

###
GET http://localhost:5000/api/v1/offers
Accept: application/json

###
GET http://localhost:5000/api/v1/entities
Accept: application/json

######################################################
# Create
POST http://localhost:5000/api/v1/items
Accept: application/json
Content-Type: application/json

{
  "name": "Camera",
  "description": "A security camera",
  "price": 125.50,
  "image": "s3://path/to/image.jpg"
}

###
POST http://localhost:5000/api/v1/offers
Accept: application/json
Content-Type: application/json

{}

###
POST http://localhost:5000/api/v1/entities
Accept: application/json
Content-Type: application/json

{
  "name": "Or Shemtov",
  "address": "HaCarmel 39, Bet Dagan, 50200, Israel",
  "phone": "0543258979",
  "email": "me@orshemtov.com"
}

######################################################
# Update
PUT http://localhost:5000/api/v1/items
Accept: application/json

{}

###
PUT http://localhost:5000/api/v1/offers
Accept: application/json

{}

###
PUT http://localhost:5000/api/v1/entities
Accept: application/json

{}

######################################################
# Delete
DELETE http://localhost:5000/api/v1/items/0
Accept: application/json

###
DELETE http://localhost:5000/api/v1/offers/0
Accept: application/json

###
DELETE http://localhost:5000/api/v1/entities/0
Accept: application/json
